# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# Customizations
your_name: Saki Shinoda
email: shinodasaki@gmail.com
title: Home
# author: Saki Shinoda
description: "Stuff by Saki Shinoda on machine learning, scientific computing, data science, programming, etc."
repository: sakishinoda/sakishinoda.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sakishinoda.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge

theme: jekyll-theme-minimal

navigation:
  - text: Home
    url: /
  # - text: Projects
  #   url: /projects/
  - text: About
    url: /about
  - text: Blog
    url: /blog/
  - text: Links
    url: /links


projects:
  - name: snlp
    description: "Code implementing attentive recurrent neural networks from Rocktaschel et al. 2016 and Logeswaran et al. 2017 for machine reading."
    link: https://github.com/sakishinoda/snlp

social:
  - service: email
    username: shinodasaki
    link: "mailto:shinodasaki@gmail.com"
  - service: github
    username: sakishinoda
    link: https://github.com/sakishinoda
  - service: twitter
    username: sakishinoda
    link: https://twitter.com/sakishinoda
  - service: linkedin
    username: sakishinoda
    link: https://www.linkedin.com/in/sakishinoda/

# Plugins
gems:
  - jekyll-seo-tag
  - jekyll-theme-minimal
  