# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# Customizations
your_name: Saki Shinoda
email: saki@shinoda.me
title: Saki Shinoda
# author: Saki Shinoda
description: > # this means to ignore newlines until "baseurl:"
  Website of Saki Shinoda. Practitioner of machine learning, scientific computing, data science, programming.
# repository: https://github.com/wemake-services/jekyll-theme-hackcss

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
# twitter_username: sakishinoda
# github_username:  sakishinoda


# Build settings
markdown: kramdown
highlighter: rouge
# markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge
# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown # choices are: 'dark', 'standard', 'markdown'

navigation:
  - text: Home
    url: /
  # - text: Projects
  #   url: /projects/
  - text: About
    url: /about/
  - text: Blog
    url: /blog/


projects:
  - name: snlp
    description: "Code implementing attentive recurrent neural networks from Rocktaschel et al. 2016 and Logeswaran et al. 2017 for machine reading."
    link: https://github.com/sakishinoda/snlp

social:
  - service: github
    username: sakishinoda
    link: https://github.com/sakishinoda
  - service: twitter
    username: sakishinoda
    link: https://twitter.com/sakishinoda

# Plugins
gems:
  - jekyll-seo-tag
