# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# Customizations
your_name: Saki Shinoda
email: saki@shinoda.me
title: Saki Shinoda
# author: Saki Shinoda
description: > # this means to ignore newlines until "baseurl:"
  Stuff by Saki Shinoda on machine learning, scientific computing, data science, programming, etc.
repository: https://github.com/sakishinoda/

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sakishinoda.github.io" # the base hostname & protocol for your site

excerpt_separator: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown # choices are: 'dark', 'standard', 'markdown'

navigation:
  - text: Home
    url: /
  # - text: Projects
  #   url: /projects/
  - text: About
    url: /about
  - text: Blog
    url: /blog/
  - text: Links
    url: /links


projects:
  - name: snlp
    description: "Code implementing attentive recurrent neural networks from Rocktaschel et al. 2016 and Logeswaran et al. 2017 for machine reading."
    link: https://github.com/sakishinoda/snlp

social:
  - service: github
    username: sakishinoda
    link: https://github.com/sakishinoda
  - service: linkedin
    username: sakishinoda
    link: https://www.linkedin.com/in/sakishinoda/

# Plugins
gems:
  - jekyll-seo-tag

theme: jekyll-theme-minimal